//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkPart2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroSkill
    {
        public int ID { get; set; }
        public int HeroID { get; set; }
        public int SkillID { get; set; }
        public double Power { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
