//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public int ID { get; set; }
        public string Nama { get; set; }
        public double Harga { get; set; }
        public int Stok { get; set; }
    }
}
