// <auto-generated />
using EsemkaPetition.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsemkaPetition.Migrations
{
    [DbContext(typeof(EsemkaPetitionContext))]
    [Migration("20240229210254_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("EsemkaPetition.Models.Petition", b =>
                {
                    b.Property<int>("PetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("PetitionID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("EsemkaPetition.Models.Signature", b =>
                {
                    b.Property<int>("SignatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetitionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SignatureID");

                    b.HasIndex("PetitionID");

                    b.HasIndex("SignerID");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("EsemkaPetition.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EsemkaPetition.Models.Petition", b =>
                {
                    b.HasOne("EsemkaPetition.Models.User", "Creator")
                        .WithMany("CreatedPetitions")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EsemkaPetition.Models.Signature", b =>
                {
                    b.HasOne("EsemkaPetition.Models.Petition", "Petition")
                        .WithMany("Signatures")
                        .HasForeignKey("PetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsemkaPetition.Models.User", "Signer")
                        .WithMany("SignedPetitions")
                        .HasForeignKey("SignerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Petition");

                    b.Navigation("Signer");
                });

            modelBuilder.Entity("EsemkaPetition.Models.Petition", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("EsemkaPetition.Models.User", b =>
                {
                    b.Navigation("CreatedPetitions");

                    b.Navigation("SignedPetitions");
                });
#pragma warning restore 612, 618
        }
    }
}
